package jogo.pkgdo.cerebro;

/*
 * Copyright (c) 2010, Oracle.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the distribution.
 *  * Neither the name of Oracle nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

/* Anagram Game Application */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTextField;
import nucleo.Constante;

/**
 * About dialog of the Anagram Game application.
 */
public class Teclado extends JDialog {

    /**
     * Creates new form About
     */
    private JTextField jtf;
    private String auxR;
    private boolean respondeu;

    public Teclado(JFrame parent, JTextField jtf, boolean respondeu) {
        super(parent, true);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        //mainPanel.setBackground(new Color(0,0,0));
        pack();
        Rectangle parentBounds = parent.getBounds();
        Dimension size = getSize();
        // Center in the parent
        int x = Math.max(0, parentBounds.x + (parentBounds.width - size.width) / 2);
        int y = Math.max(0, parentBounds.y + (parentBounds.height - size.height) / 2);

        setLocation(new Point(x + 425, y + 177));
        this.jtf = jtf;
        this.respondeu = respondeu;
        this.jtf.setText(Constante.ESPACO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton06 = new javax.swing.JButton();
        jButton04 = new javax.swing.JButton();
        jButton05 = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButton08 = new javax.swing.JButton();
        jButton09 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton01 = new javax.swing.JButton();
        jButton03 = new javax.swing.JButton();
        jButton07 = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teclado");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 350));
        getContentPane().setLayout(null);

        jButton06.setBackground(new java.awt.Color(0, 51, 153));
        jButton06.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton06.setForeground(new java.awt.Color(255, 255, 255));
        jButton06.setText("6");
        jButton06.setOpaque(false);
        jButton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton06ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton06);
        jButton06.setBounds(230, 90, 90, 70);

        jButton04.setBackground(new java.awt.Color(0, 51, 153));
        jButton04.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton04.setForeground(new java.awt.Color(255, 255, 255));
        jButton04.setText("4");
        jButton04.setOpaque(false);
        jButton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton04ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton04);
        jButton04.setBounds(40, 90, 100, 70);

        jButton05.setBackground(new java.awt.Color(0, 51, 153));
        jButton05.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton05.setForeground(new java.awt.Color(255, 255, 255));
        jButton05.setText("5");
        jButton05.setOpaque(false);
        jButton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton05ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton05);
        jButton05.setBounds(140, 90, 90, 70);

        jButtonOK.setBackground(new java.awt.Color(0, 51, 153));
        jButtonOK.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jButtonOK.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOK.setText("OK");
        jButtonOK.setOpaque(false);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK);
        jButtonOK.setBounds(230, 240, 90, 70);

        jButton08.setBackground(new java.awt.Color(0, 51, 153));
        jButton08.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton08.setForeground(new java.awt.Color(255, 255, 255));
        jButton08.setText("8");
        jButton08.setOpaque(false);
        jButton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton08ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton08);
        jButton08.setBounds(140, 170, 90, 70);

        jButton09.setBackground(new java.awt.Color(0, 51, 153));
        jButton09.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton09.setForeground(new java.awt.Color(255, 255, 255));
        jButton09.setText("9");
        jButton09.setOpaque(false);
        jButton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton09ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton09);
        jButton09.setBounds(230, 170, 90, 70);

        jButton02.setBackground(new java.awt.Color(0, 51, 153));
        jButton02.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton02.setForeground(new java.awt.Color(255, 255, 255));
        jButton02.setText("2");
        jButton02.setOpaque(false);
        jButton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton02ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton02);
        jButton02.setBounds(140, 10, 90, 70);

        jButton01.setBackground(new java.awt.Color(0, 51, 153));
        jButton01.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton01.setForeground(new java.awt.Color(255, 255, 255));
        jButton01.setText("1");
        jButton01.setOpaque(false);
        jButton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton01ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton01);
        jButton01.setBounds(40, 10, 100, 70);

        jButton03.setBackground(new java.awt.Color(0, 51, 153));
        jButton03.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton03.setForeground(new java.awt.Color(255, 255, 255));
        jButton03.setText("3");
        jButton03.setOpaque(false);
        jButton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton03ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton03);
        jButton03.setBounds(230, 10, 90, 70);

        jButton07.setBackground(new java.awt.Color(0, 51, 153));
        jButton07.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton07.setForeground(new java.awt.Color(255, 255, 255));
        jButton07.setText("7");
        jButton07.setOpaque(false);
        jButton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton07ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton07);
        jButton07.setBounds(40, 170, 100, 70);

        jButton00.setBackground(new java.awt.Color(0, 51, 153));
        jButton00.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton00.setForeground(new java.awt.Color(255, 255, 255));
        jButton00.setText("0");
        jButton00.setOpaque(false);
        jButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton00ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton00);
        jButton00.setBounds(40, 240, 100, 70);

        jButtonApagar.setBackground(new java.awt.Color(0, 51, 153));
        jButtonApagar.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jButtonApagar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApagar.setText("Apagar");
        jButtonApagar.setOpaque(false);
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(140, 240, 90, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teclado1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 310, 210);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teclado1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 10, 310, 380);

        jButton16.setBackground(new java.awt.Color(0, 51, 153));
        jButton16.setFont(new java.awt.Font("Rockwell", 0, 54)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("7");
        jButton16.setOpaque(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(40, 170, 100, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton06ActionPerformed
        // TODO add your handling code here:
        resultado(jButton06.getText());
    }//GEN-LAST:event_jButton06ActionPerformed

    private void jButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton04ActionPerformed
        // TODO add your handling code here:
        resultado(jButton04.getText());
    }//GEN-LAST:event_jButton04ActionPerformed

    private void jButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton05ActionPerformed
        // TODO add your handling code here:
        resultado(jButton05.getText());
    }//GEN-LAST:event_jButton05ActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:
        int t = jtf.getText().length();
        if (t > 0) {
            setVisible(false);
            this.respondeu = true;
            dispose();
        }

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton08ActionPerformed
        // TODO add your handling code here:
        resultado(jButton08.getText());
    }//GEN-LAST:event_jButton08ActionPerformed

    private void jButton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton09ActionPerformed
        // TODO add your handling code here:
        resultado(jButton09.getText());
    }//GEN-LAST:event_jButton09ActionPerformed

    private void jButton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton02ActionPerformed
        // TODO add your handling code here:
        resultado(jButton02.getText());
    }//GEN-LAST:event_jButton02ActionPerformed

    private void jButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton01ActionPerformed
        // TODO add your handling code here:
        resultado(jButton01.getText());

    }//GEN-LAST:event_jButton01ActionPerformed

    private void jButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton03ActionPerformed
        // TODO add your handling code here:
        resultado(jButton03.getText());
    }//GEN-LAST:event_jButton03ActionPerformed

    private void jButton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton07ActionPerformed
        // TODO add your handling code here:
        resultado(jButton07.getText());
    }//GEN-LAST:event_jButton07ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton00ActionPerformed
        // TODO add your handling code here:
        resultado(jButton00.getText());
    }//GEN-LAST:event_jButton00ActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        // TODO add your handling code here:
        apagarResultado();
    }//GEN-LAST:event_jButtonApagarActionPerformed
    public void resultado(String r) {
        auxR = jtf.getText();
        auxR += r;
        this.jtf.setText(auxR);
    }

    public void apagarResultado() {
        auxR = jtf.getText();
        if (auxR.length() > 0) {
            auxR = auxR.substring(0, auxR.length() - 1);
            this.jtf.setText(auxR);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton03;
    private javax.swing.JButton jButton04;
    private javax.swing.JButton jButton05;
    private javax.swing.JButton jButton06;
    private javax.swing.JButton jButton07;
    private javax.swing.JButton jButton08;
    private javax.swing.JButton jButton09;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
